import sqlite3
import os

home_dir = os.environ.get("HOME")
connection = sqlite3.connect(f"{home_dir}/worldmap-server/db.db")
cursor = connection.cursor()

cursor.execute('''CREATE TABLE IF NOT EXISTS leds (
               register INT,
               number INT,
               country VARCHAR(255),
               longitude INT,
               latitude INT
               );''')
print("Database leds successfully created or already exists")

cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (8, 1, 'Poland', 4, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (8, 2, 'Netherlands', 4, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (8, 4, 'UK', 4, 9)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (8, 8, 'Ireland', 4, 9)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (8, 32, 'Belarus', 4, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (8, 64, 'France', 5, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (8, 128, 'Germany', 4, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (8, 256, 'Finland', 3, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (8, 512, 'Sweden', 4, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (8, 1024, 'Norway', 3, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (8, 2048, 'Greenland', 1, 8)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (8, 4096, 'Denmark', 4, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (8, 8192, 'Lithuania', 4, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (8, 16384, 'Latvia', 4, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (8, 16384, 'Latvia', 4, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (8, 32768, 'Estonia', 4, 11)")

cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (7, 1, 'Ukraine', 5, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (7, 2, 'Hungary', 5, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (7, 4, 'Croatia', 5, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (7, 8, 'Slovakia', 5, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (7, 16, 'Greece', 6, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (7, 32, 'Albania', 5, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (7, 64, 'Montenegro', 5, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (7, 128, 'Bosnia Herzegovina', 5, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (7, 256, 'Spain', 5, 9)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (7, 512, 'Portugal', 5, 9)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (7, 1024, 'Switzerland', 5, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (7, 2048, 'Russia', 4, 12)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (7, 4096, 'Czech Republic', 4, 12)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (7, 8192, 'Austria', 5, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (7, 16384, 'Italy', 5, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (7, 32768, 'Slovenia', 5, 10)")

cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (6, 1, 'Mali', 7, 8)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (6, 2, 'Gambia', 7, 8)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (6, 4, 'Senegal', 7, 8)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (6, 8, 'Mauritania', 6, 8)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (6, 16, 'Libya', 6, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (6, 32, 'Tunisia', 6, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (6, 64, 'Algeria', 6, 9)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (6, 128, 'Marocco', 5, 9)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (6, 256, 'Turkey', 6, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (6, 512, 'Romania', 5, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (6, 1024, 'Bulgaria', 5, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (6, 2048, 'North Macedonia', 5, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (6, 4096, 'Syria', 6, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (6, 8192, 'Georgia', 5, 12)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (6, 16384, 'Jordan', 6, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (6, 32768, 'Libanon', 6, 11)")

cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (5, 1, 'Ethiopia', 8, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (5, 2, 'South Sudan', 8, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (5, 4, 'Somalia', 8, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (5, 8, 'Central Africa', 8, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (5, 16, 'Chad', 7, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (5, 32, 'Benin', 8, 9)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (5, 64, 'Nigeria', 7, 9)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (5, 128, 'Cameroon', 8, 9)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (5, 256, 'Burkina Faso', 7, 9)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (5, 512, 'Niger', 7, 9)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (5, 1024, 'Togo', 7, 9)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (5, 2048, 'Ghana', 8, 9)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (5, 4096, 'Guinea', 7, 8)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (5, 8192, 'Sierra Leone', 7, 8)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (5, 16384, 'Liberia', 7, 8)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (5, 32768, 'Ivory Coast', 7, 8)")

cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (4, 1, 'Tanzania', 9, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (4, 2, 'Malabi', 9, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (4, 4, 'Democratic Rupublic of Congo', 9, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (4, 8, 'Congo', 9, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (4, 16, 'Uganda', 8, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (4, 32, 'Kenya', 8, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (4, 64, 'Equatorial Guinea', 8, 9)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (4, 128, 'Gabon', 8, 9)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (4, 256, 'Mozambique', 10, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (4, 512, 'Botswana', 10, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (4, 1024, 'South Africa', 10, 9)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (4, 2048, 'Namibia', 10, 9)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (4, 4096, 'Zambia', 9, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (4, 8192, 'Zimbabwe', 9, 10)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (4, 16384, 'Angola', 9, 9)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (4, 32768, 'Madagaskar', 10, 11)")

cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (3, 1, 'Iraq', 6, 12)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (3, 2, 'Azerbaijan', 6, 12)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (3, 4, 'Iran', 6, 12)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (3, 8, 'Turkmenistan', 6, 12)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (3, 16, 'India', 7, 14)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (3, 32, 'Pakistan', 7, 13)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (3, 64, 'Afghanistan', 7, 13)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (3, 128, '', -1, -1)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (3, 256, 'United Arab Emirates', 7, 12)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (3, 512, 'Saudi Arabia', 7, 12)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (3, 1024, 'Oman', 7, 12)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (3, 2048, 'Yemen', 8, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (3, 4096, 'Egypt', 6, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (3, 8192, 'Sudan', 7, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (3, 16384, 'Eritrea', 7, 11)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (3, 32768, 'Dschibuti', 8, 11)")

cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (2, 1, 'China', 7, 16)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (2, 2, 'North Korea', 7, 16)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (2, 4, 'South Korea', 7, 16)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (2, 8, '', -1, -1)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (2, 16, 'Nepal', 7, 14)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (2, 32, 'Bangladesh', 8, 14)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (2, 64, 'Malaysia', 9, 15)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (2, 128, 'Papua New Guinea', 10, 17)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (2, 256, 'Cambodia', 9, 15)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (2, 512, 'Thailand', 8, 14)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (2, 1024, 'Indonesia', 9, 14)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (2, 2048, '', -1, -1)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (2, 4096, 'Australia', 12, 16)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (2, 8192, 'Laos', 8, 15)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (2, 16384, 'Vietnam', 8, 15)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (2, 32768, 'Myanmar', 8, 14)")

cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (1, 1, 'Belize', 7, 3)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (1, 2, 'Honduras', 7, 3)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (1, 4, 'Guatemala', 7, 3)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (1, 8, 'Mexico', 7, 3)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (1, 16, '', -1, -1)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (1, 32, '', -1, -1)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (1, 64, 'USA', 6, 4)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (1, 128, 'Canada', 5, 5)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (1, 256, 'Uzbekistan', 6, 13)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (1, 512, 'Kirgyztan', 6, 14)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (1, 1024, 'Kazakhstan', 5, 13)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (1, 2048, 'Mongolia', 5, 15)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (1, 4096, '', -1, -1)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (1, 8192, '', -1, -1)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (1, 16384, '', -1, -1)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (1, 32768, '', -1, -1)")

cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (0, 1, 'Brazil', 9, 6)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (0, 2, 'Paraguay', 10, 6)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (0, 4, 'Uruguay', 10, 6)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (0, 8, 'Argentina', 10, 6)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (0, 16, 'French Guyana', 8, 6)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (0, 32, 'Peru', 9, 5)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (0, 64, 'Bolivia', 9, 5)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (0, 128, 'Chile', 11, 5)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (0, 256, 'Venezuela', 8, 5)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (0, 512, 'Guyana', 8, 6)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (0, 1024, 'Suriname', 8, 6)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (0, 2048, 'Ecuador', 8, 4)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (0, 4096, 'Nicaragua', 7, 3)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (0, 8192, 'Costa Rica', 8, 4)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (0, 16384, 'Panama', 8, 4)")
cursor.execute("INSERT INTO leds (register, number, country, longitude, latitude) VALUES (0, 32768, 'Columbia', 8, 4)")

cursor.execute('''CREATE TABLE IF NOT EXISTS neopixels (
               number INT,
               longitude INT,
               latitude INT
               );''')
print("Database neopixels successfully created or already exists")

cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (0, 2, 15)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (1, 2, 14)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (2, 3, 13)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (3, 3, 12)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (4, 2, 11)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (5, 1, 8)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (6, 3, 7)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (7, 3, 6)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (8, 2, 6)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (9, 0, 7)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (10, 0, 8)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (11, 3, 10)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (12, 4, 10)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (13, 5, 9)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (14, 5, 10)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (15, 6, 11)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (16, 6, 10)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (17, 9, 10)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (18, 6, 7)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (19, 7, 8)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (20, 8, 9)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (21, 9, 9)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (22, 9, 9)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (23, 10, 10)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (24, 9, 11)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (25, 8, 11)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (26, 7, 11)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (27, 7, 11)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (28, 8, 12)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (29, 7, 12)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (30, 8, 13)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (31, 8, 14)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (32, 9, 14)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (33, 11, 16)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (34, 12, 15)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (35, 12, 16)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (36, 12, 17)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (37, 11, 17)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (38, 9, 15)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (39, 10 ,16)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (40, 8, 15)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (41, 7, 16)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (42, 6, 16)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (43, 5, 17)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (44, 4, 18)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (45, 5, 18)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (46, 4, 19)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (47, 3, 19)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (48, 3, 17)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (49, 3, 16)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (50, 6, 3)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (51, 6, 4)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (52, 5, 4)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (53, 4, 5)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (54, 3, 5)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (55, 4, 4)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (56, 4, 4)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (57, 3, 4)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (58, 2, 5)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (59, 3, 5)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (60, 2, 4)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (61, 2, 4)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (62, 2, 3)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (63, 2, 3)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (64, 1, 2)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (65, 1, 1)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (66, 2, 0)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (67, 3, 1)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (68, 4, 1)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (69, 5, 1)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (70, 6, 2)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (71, 7, 3)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (72, 7, 4)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (73, 8, 4)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (74, 9, 5)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (75, 10, 5)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (76, 11, 6)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (77, 11, 6)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (78, 10, 6)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (79, 9, 7)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (80, 8, 6)")
cursor.execute("INSERT INTO neopixels (number, longitude, latitude) VALUES (81, 7, 5)")

connection.commit()
connection.close()